#ifndef PRT_BESTFIT_LITTLE_SLAB_H
#define PRT_BESTFIT_LITTLE_SLAB_H

#include "prt_bestfit_little_compat.h"

#define SLAB_MEM_ALLOCATOR_SIZE 512U
#define SLAB_BASIC_NEED_SIZE 0x1000U

#ifdef LOSCFG_KERNEL_MEM_SLAB_AUTO_EXPANSION_MODE
enum SlabBucketSizeType {
    SLAB_BUCKET_SIZE_HALF_OF_HEAP = 0x1UL,
    SLAB_BUCKET_SIZE_QUARTER_OF_HEAP,
    SLAB_BUCKET_SIZE_TYPE_MAX
};

#define SLAB_MEM_BUCKET_SIZE_TYPE SLAB_BUCKET_SIZE_HALF_OF_HEAP
#endif

extern VOID PRT_BestfitLittleSlabSizeCfg(UINT32 *cfg, UINT32 cnt);

#endif /* PRT_BESTFIT_LITTLE_SLAB_H */
