/*
 * Copyright (c) Hisilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
 * UniProton is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 * 	http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * See the Mulan PSL v2 for more details.
 */

#ifndef __DEVICE_RESOURCE_H__
#define __DEVICE_RESOURCE_H__

#define DT_N_S_SOC_S_DMAC_P_DOMAIN_CHANNEL0_EXISTS 1
#define DT_N_S_SOC_S_DMAC_P_DOMAIN_CHANNEL1_EXISTS 1
#define DT_N_S_SOC_S_DMAC_P_DOMAIN_CHANNEL2_EXISTS 1
#define DT_N_S_SOC_S_DMAC_P_DOMAIN_CHANNEL3_EXISTS 1
#define DT_N_S_SOC_S_DMAC_P_DOMAIN_CHANNEL4_EXISTS 1
#define DT_N_S_SOC_S_DMAC_P_DOMAIN_CHANNEL5_EXISTS 1
#define DT_N_S_SOC_S_DMAC_P_DOMAIN_CHANNEL6_EXISTS 1
#define DT_N_S_SOC_S_DMAC_P_DOMAIN_CHANNEL7_EXISTS 1
#define DT_N_S_SOC_S_GMAC_P_DOMAIN_GMAC0_EXISTS 1
#define DT_N_S_SOC_S_GMAC_P_DOMAIN_GMAC3_EXISTS 1
#define DT_N_S_SOC_S_GPIO_P_DOMAIN_GPIO0_EXISTS 1
#define DT_N_S_SOC_S_GPIO_P_DOMAIN_GPIO1_EXISTS 1
#define DT_N_S_SOC_S_GPIO_P_DOMAIN_GPIO2_EXISTS 1
#define DT_N_S_SOC_S_GPIO_P_DOMAIN_GPIO3_EXISTS 1
#define DT_N_S_SOC_S_I2C_P_DOMAIN_I2C3_EXISTS 1
#define DT_N_S_SOC_S_I2C_P_DOMAIN_I2C4_EXISTS 1
#define DT_N_S_SOC_S_I2C_P_DOMAIN_I2C5_EXISTS 1
#define DT_N_S_SOC_S_I2C_P_DOMAIN_I2C6_EXISTS 1
#define DT_N_S_SOC_S_I2C_P_DOMAIN_I2C7_EXISTS 1
#define DT_N_S_SOC_S_I2C_P_DOMAIN_I2C8_EXISTS 1
#define DT_N_S_SOC_S_I2C_P_DOMAIN_I2C9_EXISTS 1
#define DT_N_S_SOC_S_I2C_P_DOMAIN_I2C10_EXISTS 1
#define DT_N_S_SOC_S_I2C_P_DOMAIN_I2C11_EXISTS 1
#define DT_N_S_SOC_S_I2C_P_DOMAIN_I2C12_EXISTS 1
#define DT_N_S_SOC_S_I2C_P_DOMAIN_I2C13_EXISTS 1
#define DT_N_S_SOC_S_I2C_P_DOMAIN_I2C14_EXISTS 1
#define DT_N_S_SOC_S_I2C_P_DOMAIN_I2C15_EXISTS 1
#define DT_N_S_SOC_S_LOCALBUS_P_DOMAIN_LOCALBUS0_EXISTS 1
#define DT_N_S_SOC_S_SPI_P_DOMAIN_SPI1_EXISTS 1
#define DT_N_S_SOC_S_TIMER_P_DOMAIN_TIMER3_EXISTS 1
#define DT_N_S_SOC_S_TIMER_P_DOMAIN_TIMER4_EXISTS 1
#define DT_N_S_SOC_S_TIMER_P_DOMAIN_TIMER5_EXISTS 1
#define DT_N_S_SOC_S_UART_P_DOMAIN_UART2_EXISTS 1
#define DT_N_S_SOC_S_UART_P_DOMAIN_UART3_EXISTS 1
#define DT_N_S_SOC_S_UART_P_DOMAIN_UART4_EXISTS 1
#define DT_N_S_SOC_S_WATCHDOG_P_DOMAIN_WATCHDOG2_EXISTS 1
#define DT_N_S_SOC_S_WATCHDOG_P_DOMAIN_WATCHDOG3_EXISTS 1
#define DT_N_S_SOC_S_WATCHDOG_P_DOMAIN_WATCHDOG4_EXISTS 1
#endif /* __DEVICE_RESOURCE_H__ */

